### ISSUE TITLE
Cannot find module .../@stencil/core/bin/logger

### ISSUE THREAD

**Issue by paulmeller** [ionic-team/stencil-ssr-starter#1]
I'm getting an error when I run the Express app (npm run start:ssr):
Error: Cannot find module '/{...}/node_modules/@stencil/core/bin/logger'

I have installed all dependencies including logger.

Any ideas?

**Comment by ihadeed** [comment]
The core package hasn't been updated yet on npm. To make this repo work, you need to edit `node_modules/@stencil/core/dist/server/index.js` and replace this:
```ts
require(path.join(__dirname, '../../bin/logger'));
```
With this:
```ts
require(path.join(__dirname, '../../bin/util')).logger;
```

**Comment by paulmeller** [comment]
Thanks for this - the script is now running, but, the renderer.hydrateToString function isn't responding.

**Comment by lowe0292** [comment]
I'm observing the same behavior as @paulmeller above after implementing @ihadeed's workaround: the express server gets to the `renderer.hydrateToString` line, but the page doesn't load.

**Comment by mitchellsimoens** [comment]
This is also fixed over at ionic-team/stencil repo via this issue: ionic-team/stencil#147 and PR ionic-team/stencil#159

**Comment by adamdbradley** [comment]
Latest updates now use the ssr middleware.
